### ISSUE TITLE
How can I add custom css classes?

### ISSUE THREAD

**Issue by guangzhun** [AlexStack/nextjs-materia-mui-typescript-hook-form-scaffold-boilerplate-starter#2]
I built the project by using React.js but because of some reasons, I want to convert it into next.js. In react project, I added some CSS classes.

.expired-notice {
  text-align: center;
  padding: 2rem;
  border: 1px solid #ebebeb;
  border-radius: 0.25rem;
  margin: 0.5rem;
}

.expired-notice > span {
  font-size: 2.5rem;
  font-weight: bold;
  color: red;
}

.expired-notice > p {
  font-size: 1.5rem;
}

.show-counter .countdown-link {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  font-size: 1.25rem;
  line-height: 1.75rem;
  border-radius: 0.25rem;
  text-decoration: none;
  color: #fff;
}

.show-counter .countdown {
  line-height: 1.25rem;
  padding: 0.75rem;
  align-items: center;
  display: flex;
  flex-direction: column;
  border-radius: 16px;
  width: 65px;
  height: 65px;
  margin: 3px;
}

.show-counter .countdown.danger {
  color: #ff0000;
}

.show-counter .countdown > p {
  margin: 5px 0;
}

.show-counter .countdown > span {
  text-transform: uppercase;
  font-size: 0.6rem;
  line-height: 1rem;
  color: black;
}

These are the CSS classes I want to add. Where can I put these?

**Comment by AlexStack** [comment]
You can put them into a global style variable: src/styles/index.ts
